# Datadog Agent with Logs, APM, Processes, and System Probe enabled
targetSystem: "linux"
datadog:
  apiKeyExistingSecret: <DATADOG_API_KEY_SECRET>
  appKeyExistingSecret: <DATADOG_APP_KEY_SECRET>
  clusterName: <CLUSTER_NAME>
  site: datadoghq.com
  tags:
    - "env:uat"

  kubelet:
    tlsVerify: false

  kubeStateMetricsEnabled: false
  kubeStateMetricsCore:
    enabled: true
  operator:
    enabled: false

  logs:
    enabled: true
    containerCollectAll: true
    containerCollectUsingFiles: true
    
  env:
    - name: DD_PROXY_HTTPS
      value: "http://10.27.208.188:8080"
    - name: DD_PROXY_HTTP
      value: "http://10.27.208.188:8080"
    - name: DD_NO_PROXY_NONEXACT_MATCH
      value: "true"
    - name: DD_PROXY_NO_PROXY
      value: "127.0.0.0/8 10.0.0.0/8 172.16.0.0/12 192.168.0.0/16"    

  apm:
    instrumentation:
      enabled: true
      targets:
        - name: "namespaceselector"
          namespaceSelector:
            matchNames:
              - "singlestepinstrumentation"
          ddTraceVersions:
            java: "latest"
            js: "latest"

  kubernetesResourcesLabelsAsTags:
    pods:
      app: service
      app.kubernetes.io/name: service
    deployments.apps:
      app: service

  dogstatsd:
    port: 8125
    useHostPort: true
    nonLocalTraffic: true

  processAgent:
    enabled: true
    processCollection: true

  networkMonitoring:
    enabled: true

agents:
  tolerations:
    - key: node-role.kubernetes.io/master
      effect: NoSchedule
